[tool.poetry]
name = "discord-quest-bot"
version = "0.1.0"
description = "Discord bot for tracking and rewarding tasks"
authors = ["jplhanna <jpl.hanna@gmail.com>"]
readme = "README.md"
packages = [{ include = "local_server" }]

[tool.poetry.dependencies]
python = "^3.10"
alembic = "^1.8"
psycopg2 = "^2.9.3"
furl = "^2.1.3"
asyncpg = "0.26.0"
dependency-injector = ">=4, <5"
SQLAlchemy = { extras = ["asyncio", "mypy"], version = "^1.4.39" }
"discord.py" = "^2.0.1"


[tool.poetry.group.dev.dependencies]
mypy = "*"
pytest = "*"
pylint = "*"
pre-commit = "*"
flake8 = "*"
black = "*"
sqlalchemy-stubs = "*"
pytest-asyncio = "*"
faker = "*"
coverage = "*"
pytest-async-sqlalchemy = "*"
asynctest = "*"
pytest-randomly = "*"
pytest-cov = "*"
bandit = "^1.7.4"
flake8-pytest-style = "^1.6.0"
"discord.py-stubs" = "*"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.pylint."MASTER"]
max-line-length = 120
ignore = ["alembic", "tests", "conftest.py"]

[tool.pylint."MESSAGES CONTROL"]
disable = ["too-few-public-methods",
    "too-many-locals",
    # docstring
    "missing-class-docstring",
    "missing-function-docstring",
    "missing-module-docstring",
    # allow disabling Pylin locally
    "locally-disabled"]

[tool.pylint."TYPE CHECK"]
ignored-modules = ["dependency_injector.providers", "dependency_injector.containers"]

[tool.pylint."REPORTS"]
msg-template = "{path}:{line}: [{msg_id}, {obj}] {msg} ({symbol})"

[tool.bandit]
exclude_dirs = ["test"]
