[tool.poetry]
name = "discord-quest-bot"
version = "0.1.1"
description = "Discord bot for tracking and rewarding tasks"
authors = ["jplhanna <jpl.hanna@gmail.com>"]
readme = "README.md"
packages = [{ include = "local_server" }]

[tool.poetry.dependencies]
python = "^3.11"
alembic = "^1.8"
furl = "^2.1.3"
asyncpg = "0.27.0"
dependency-injector = ">=4, <5"
SQLAlchemy = { version = "^2.0.0b3", allow-prereleases = true }
"discord.py" = "^2.0.1"
psycopg2-binary = "^2.9.6"


[tool.poetry.group.dev.dependencies]
mypy = "*"
pytest = "*"
pre-commit = "*"
flake8 = "*"
black = "*"
pytest-asyncio = "*"
faker = "*"
coverage = { extras = ["toml"], version = "^6.4.4" }
pytest-async-sqlalchemy = "*"
asynctest = "*"
pytest-randomly = "*"
pytest-cov = "*"
bandit = { extras = ["toml"], version = "^1.7.4" }
flake8-pytest-style = "^1.6.0"
Flake8-pyproject = "^1.1.0.post0"
ruff = "^0.0.280"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.ruff]
select = ["E", "F", "W", "C"]
fixable = ["ALL"]
exclude = ["alembic"]

line-length = 120

target-version = "py310"

[tool.bandit]
exclude_dirs = ["test"]

[tool.mypy]
exclude = [
    "test",
    "alembic"
]
namespace_packages = true
python_version = "3.10"
disallow_untyped_defs = true
disallow_incomplete_defs = true
warn_redundant_casts = true
warn_unused_ignores = true
warn_return_any = true
warn_unreachable = true
show_error_codes = true
local_partial_types = true
plugins = ["sqlalchemy.ext.mypy.plugin"]

[[tool.mypy.overrides]]
module = "sqlalchemy.*"
ignore_missing_imports = true
disallow_untyped_calls = false

[[tool.mypy.overrides]]
module = "furl"
ignore_missing_imports = true

[tool.black]
line-length = 120

[tool.pytest.ini_options]
asyncio_mode = "auto"
filterwarnings = [
    "ignore::DeprecationWarning"
]
markers = [
    "integration"
]

[tool.coverage.run]
branch = true
omit = [
    "alembic/*",
    "run.py",
    "config.py",
    "conftest.py",
    "constants.py"
]

[tool.coverage.report]
skip_empty = true

[tool.flake8]
max-line-length = 120
