[tool.poetry]
name = "local-server"
version = "0.1.0"
description = "Discord bot for tracking and rewarding tasks"
authors = ["jplhanna <jpl.hanna@gmail.com>"]
readme = "README.md"
packages = [{ include = "local_server" }]

[tool.poetry.dependencies]
python = "^3.10"
discord = "*"
"discord.py-stubs" = "*"
alembic = "*"
psycopg2 = "*"
furl = "*"
asyncpg = "*"
dependency-injector = ">=4, <5"
SQLAlchemy = { extras = ["asyncio", "mypy"], version = "^1.4.39" }


[tool.poetry.group.dev.dependencies]
mypy = "*"
pytest = "*"
pylint = "*"
pre-commit = "*"
flake8 = "*"
black = "*"
sqlalchemy-stubs = "*"
pytest-asyncio = "*"
faker = "*"
coverage = "*"
pytest-async-sqlalchemy = "*"
asynctest = "*"
pytest-randomly = "*"
pytest-cov = "*"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
