NEW_USER_MESSAGE = "You have been registered, prepare for adventure!"
ALREADY_REGISTERED_MESSAGE = "You have already registered"
REGISTER_FIRST_MESSAGE = "Please register first"
NO_MENU_THIS_WEEK_MESSAGE = "No menu has been created for this week."
SERVER_ONLY_BAD_REQUEST_MESSAGE = "Bad request, this feature is only available in servers."
NO_MENU_ITEMS_FOR_CHOSEN_DAY_MESSAGE = "No items to select for the day you asked."
