"""empty message

Revision ID: 2f0c6e712786
Revises: d67cfff45d3f
Create Date: 2023-01-15 02:37:52.622519

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "2f0c6e712786"
down_revision = "d67cfff45d3f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_quest")
    op.create_table(
        "user_quest",
        sa.Column("quest_id", sa.Integer(), nullable=False),
        sa.Column("date_completed", sa.DateTime(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("datetime_created", sa.DateTime(), nullable=False),
        sa.Column("datetime_edited", sa.DateTime(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["quest_id"], ["quest.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_user_quest_quest_id"),
        "user_quest",
        ["quest_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_quest_quest_id"), table_name="user_quest")
    op.drop_table("user_quest")
    # ### end Alembic commands ###
