"""Introduce menu tables

Revision ID: 4232a8d67776
Revises: 2f0c6e712786
Create Date: 2024-02-06 02:34:23.627469

"""

from alembic import op
import sqlalchemy as sa
import sqlmodel

from src.constants import DayOfWeek
from src.helpers.sqlalchemy_helpers import EnumColumn

# revision identifiers, used by Alembic.
revision = "4232a8d67776"
down_revision = "2f0c6e712786"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "menu",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("datetime_created", sa.DateTime(), nullable=False),
        sa.Column("datetime_edited", sa.DateTime(), nullable=False),
        sa.Column("server_id", sa.Integer(), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "menu_item",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("datetime_created", sa.DateTime(), nullable=False),
        sa.Column("datetime_edited", sa.DateTime(), nullable=False),
        sa.Column("food", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("day_of_the_week", EnumColumn(DayOfWeek), nullable=True),
        sa.Column("menu_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["menu_id"],
            ["menu.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_constraint("user_quest_quest_id_fkey", "user_quest", type_="foreignkey")
    op.create_foreign_key(None, "user_quest", "quest", ["quest_id"], ["id"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "user_quest", type_="foreignkey")
    op.create_foreign_key("user_quest_quest_id_fkey", "user_quest", "quest", ["quest_id"], ["id"], ondelete="CASCADE")
    op.drop_table("menu_item")
    op.drop_table("menu")
    # ### end Alembic commands ###
