"""Update server id to big int

Revision ID: 9deebb8552c0
Revises: 4232a8d67776
Create Date: 2024-02-06 06:16:05.689061

"""

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = "9deebb8552c0"
down_revision = "4232a8d67776"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("menu", "server_id", existing_type=sa.INTEGER(), type_=sa.BigInteger(), existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("menu", "server_id", existing_type=sa.BigInteger(), type_=sa.INTEGER(), existing_nullable=False)
    # ### end Alembic commands ###
