"""empty message

Revision ID: d67cfff45d3f
Revises: 76bd75f57769
Create Date: 2023-01-15 01:58:31.273578

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "d67cfff45d3f"
down_revision = "76bd75f57769"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user_quest", sa.Column("date_completed", sa.DateTime(), nullable=True))
    op.add_column("user_quest", sa.Column("id", sa.Integer(), nullable=False))
    op.add_column(
        "user_quest",
        sa.Column("datetime_created", sa.DateTime(), nullable=False),
    )
    op.add_column(
        "user_quest",
        sa.Column("datetime_edited", sa.DateTime(), nullable=False),
    )
    op.create_index(
        op.f("ix_user_quest_quest_id"),
        "user_quest",
        ["quest_id"],
        unique=False,
    )
    op.drop_constraint("user_quest_user_id_fkey", "user_quest", type_="foreignkey")
    op.create_foreign_key(None, "user_quest", "user", ["user_id"], ["id"])
    op.drop_column("user_quest", "completed")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user_quest",
        sa.Column(
            "completed",
            sa.BOOLEAN(),
            server_default=sa.text("false"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_constraint(None, "user_quest", type_="foreignkey")
    op.create_foreign_key(
        "user_quest_user_id_fkey",
        "user_quest",
        "user",
        ["user_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_index(op.f("ix_user_quest_quest_id"), table_name="user_quest")
    op.drop_column("user_quest", "datetime_edited")
    op.drop_column("user_quest", "datetime_created")
    op.drop_column("user_quest", "id")
    op.drop_column("user_quest", "date_completed")
    # ### end Alembic commands ###
