QUEST_COLUMN_NAME = "Quests"
EXPERIENCE_COLUMN_NAME = "XP"
BOX_WRAPPER_CHAR = "="
BOX_SIDE_CHAR = "||"
PRE_TEXT = BOX_SIDE_CHAR + "  "
POST_TEXT = "  " + BOX_SIDE_CHAR
CODE_BLOCK = "```"
WRAPPER_TEXT_LEN = len(POST_TEXT) + len(PRE_TEXT)
MINIMUM_SPACING = 2
