QUEST_COLUMN_NAME = "Quests"
EXPERIENCE_COLUMN_NAME = "XP"
BOX_VERTICAL_CHAR = "="
BOX_SIDE_CHAR = "||"
BLOCK_PRE_TEXT = BOX_SIDE_CHAR + "  "
BLOCK_POST_TEXT = "  " + BOX_SIDE_CHAR
CODE_BLOCK = "```"
WRAPPER_TEXT_LEN = len(BLOCK_POST_TEXT) + len(BLOCK_PRE_TEXT)
MINIMUM_SPACING = 2
