# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

permissions:
  contents: read

env:
  DATABASE_USER: db_bot
  TEST_DATABASE_NAME: test_db

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: '3.10'
      - name: Build Docker images
        run: docker-compose build test-pipeline
      - name: Lint with pylint
        run: docker-compose run test-pipeline pylint ../app
      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          docker-compose run test-pipeline flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The project standard line length is 120
          docker-compose run test-pipeline flake8 . --count --exit-zero --max-complexity=10 --max-line-length=120 --statistics
      - name: Test with unit pytest
        run: |
          docker-compose run test-pipeline pytest -m "not integration" --doctest-modules --junitxml=junit/test-results.xml --cov=com --cov-report=xml --cov-report=html
      - name: Test with integration pytest
        run: |
          docker-compose run test-pipeline pytest -m integration --doctest-modules --junitxml=junit/test-results.xml --cov=com --cov-report=xml --cov-report=html
