# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

env:
  DATABASE_USER: db_bot
  DATABASE_PASSWORD: test_p
  TEST_DATABASE_NAME: test_db

jobs:
  test-pipeline:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.1.4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Build Docker images
        run: |
          docker compose build test-pipeline
          docker compose up -d test-pipeline
      - name: Check format with ruff
        if: always()
        run: docker compose exec test-pipeline ruff format --check
      - name: Check type hints
        if: always()
        run: docker compose exec test-pipeline mypy src
      - name: Lint with ruff
        if: always()
        run: docker compose exec test-pipeline ruff check src
      - name: Test with unit pytest
        if: always()
        run: |
          docker compose exec test-pipeline pytest --cov-report=xml --cov=.
